name: Auto Rollup Build

on:
  push:
    paths:
      - "src/**"
      - "rollup.config.js"
      - "package.json"
      - "package-lock.json"
      - "babel.config.json"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Rollup
        run: npx rollup -c
        env:
          BRANCH: ${{ github.ref_name }}

      - name: Commit & push build (beta branch only)
        if: github.ref == 'refs/heads/beta'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add yet-another-media-player-beta.js || true
          git diff --cached --quiet || git commit -m "Auto-build: beta rollup output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit & push build (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add yet-another-media-player.js || true
          git diff --cached --quiet || git commit -m "Auto-build: main rollup output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment on commit (beta branch only)
        if: github.ref == 'refs/heads/beta'
        run: |
          echo "✅ Beta branch build completed successfully!"
          echo "📦 Ready for merge to main using automated workflow"
          echo "🔗 Go to Actions → 'Beta to Main Merge' to proceed"
