name: Sync Config Files to Beta

on:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "rollup.config.js"
      - "babel.config.json"
      - ".github/workflows/sync-config-to-beta.yaml"
  workflow_dispatch:

jobs:
  sync-config-to-beta:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout beta branch
        run: git checkout beta

      - name: Pull latest beta changes
        run: git pull origin beta

      - name: Sync config files from main
        run: |
          # Get the latest config files from main branch
          git checkout origin/main -- package.json package-lock.json rollup.config.js babel.config.json
          
          # Check if there are any changes
          if git diff --quiet; then
            echo "No config file changes to sync"
          else
            echo "Syncing config files from main to beta"
          fi

      - name: Commit and push config sync
        run: |
          # Only commit if there are changes
          if ! git diff --quiet; then
            git add package.json package-lock.json rollup.config.js babel.config.json
            git commit -m "Sync config files from main branch

            - Updated package.json dependencies
            - Updated package-lock.json
            - Updated rollup.config.js
            - Updated babel.config.json
            
            Auto-synced from main branch to keep beta up to date"
            git push origin beta
            echo "✅ Config files synced from main to beta"
          else
            echo "✅ No config changes to sync"
          fi

      - name: Trigger beta rollup build
        if: success()
        run: |
          # Only trigger if we actually pushed changes
          if git log --oneline origin/beta..HEAD | grep -q "Sync config files"; then
            echo "🔄 Triggering beta rollup build with updated config"
            # The rollup workflow will automatically trigger due to the push
          else
            echo "⏭️  Skipping rollup trigger - no config changes"
          fi
